#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn lint-staged &&
git diff --quiet --cached src/assets/blog || (echo "⚠️  Blog folder changed, generating open graph images" && yarn generate-og-images && git add -A)